### PR TITLE
CMakeLists has been rewritten.

### PR DESCRIPTION
**Pull request by MateuszMiekicki**
The build system for a single solution has been improved. GLOB has been abandoned because of its consequences. IMO it is not worth pushing it here. The formatting of the code has been slightly improved to be more uniform.

### CODE REVIEW

**Comment by jaroslawroszyk** [comment]
thanks

**Comment by jaroslawroszyk** [comment]
But what is this #TODO from file? and msfc?

**Comment by MateuszMiekicki** [comment]
> But what is this #TODO from file? and msfc?

Msvc has a different set of flags than gcc/clang. You will need to read up on them and add them in the future.

**Comment by jaroslawroszyk** [comment]
okey i will try

**Pull request merged**
